version: "2"

services:
  web:
    extends:
      file: docker-compose-common.yml
      service: web
    ports:
      - "20000:80"
    links:
      - "db:db"
  db:
    extends:
      file: docker-compose-common.yml
      service: db
    volumes:
      - "./.data/db:/var/lib/mysql"
    ports:
      - '20001:3306'
