version: "2"

services:
  web:
    extends:
      file: docker-compose-common.yml
      service: web
    ports:
      - "10000:80"
      - "10005:8089"
    links:
      - "db:db"
  db:
    extends:
      file: docker-compose-common.yml
      service: db
    volumes:
      - "./.data/db:/var/lib/mysql"
    ports:
      - '10001:3306'
